### ISSUE TITLE
TypeORM 패턴 결정

### ISSUE THREAD

**Issue by earthkingman** [earthkingman/NodeJS-React-42StackOverFlow#1]
Active Record Pattern
모델 그 자체에 쿼리 메소드를 정의하고, 모델의 메소드를 사용하여 객체를 저장, 제거, 불러오는 방식

Data MapperPattern
분리된 클래스에 쿼리 메소드를 정의하는 방식 Repository를 이용하여 객체를 저장, 제거, 불러오는 방식

어떤 방식을 사용할지 정합시다.

**Comment by hainho** [comment]
### data mapper 패턴 사용시

**ddd vs cqrs**

ddd (Domain Driven Design)
데이터 관련된 코드들을 기능을 기준으로 나누어 설계하는 방식

cqrs (Command and Query Responsibility Segregation)
커맨드 (insert, update, delete)와 쿼리(select)로 나누어 설계하는 방식

### cqrs 사용시

**일반 vs 프리미엄 vs 디럭스**

일반
데이터 접근 방식만 나누어 설계하는 방식
데이터 베이스는 하나를 사용하기 때문에 성능상 이점은 없음
![](http://www.popit.kr/wp-content/uploads/2016/09/CQRS2.png)

프리미엄
데이터 베이스도 분리하고 이 둘을 broker를 통해 data 동기화 처리 하는 방식
성능 향상 가능 하지만 동기화 처리를 위한 broker의 가용성과 신뢰도가 보장되어야함
![](http://www.popit.kr/wp-content/uploads/2016/09/CQRS3-364x600.png)

디럭스
이벤트 소싱을 적용한 구조 (이벤트 스트림을 별도의 데이터베이스에 저장하는 방식)
이벤트 소싱의 이벤트 스트림은 오직 추가만 가능하고 이를 필요로 하는 시점에서 구체화 단계를 거친다
이런 처리 구조가 cqrs의 모델 분리 관점과 상당한 시너지가 있어 대부분 cqrs 패턴 적용시 이벤트 소싱이 적용된 구조를 선택한다
![](http://www.popit.kr/wp-content/uploads/2016/09/CQRS_6_CQRS_ES-300x140.png)

**Comment by earthkingman** [comment]
https://github-wiki-see.page/m/boostcamp-2020/Project12-B-Slack-Web/wiki/TypeORM
참고해서 현재 작성된 Active Record 패턴에서  Data Mapper 패턴으로 바꾸겠습니다.
