### ISSUE TITLE
BasicTemplate 논의

### ISSUE THREAD

**Issue by Chloekkk** [earthkingman/NodeJS-React-42StackOverFlow#141]
### 이슈에 대한 설명
- BasicTemplate 의도 자체가 공통 컴포넌트인 헤더와 푸터의 고정된 컴포넌트 제작
- header props 로 따로 받을 이유??
- Basic Template 안에서 합쳐버리는건 어떨까???

- content 부분을 아예 `children` 으로 받아서 처리해버리기
- 이유: content 를 props 로 받아서 처리해버리면 content 크기가 커져버릴 경우 코드 가독성이 떨어짐
- content 를 children 으로 처리할 경우 하위 컴포넌트로 넣어서 코드 가독성이 더 올라가지 않을까??

### checkList
- BasicTemplate 의존성
- Main, Detail, Writing 등등 의존성 파악 및 수정

**Comment by Yenowme** [comment]
## 해결방안

- header props 따로 주지 않고 내부에서 사용함
- content 부분을 아예 children 으로 받아서 처리
- 하단 마진 늘이기

### 의존성 확인

- [ ] Mainpage
  - 상단 패딩 없애기
- [ ] Detailpage
- [ ] Writingpage
- [ ] Settingpage

**Comment by Chloekkk** [comment]
전체 수정 완료하였습니다
