### ISSUE TITLE
formdata with no file cause error

### ISSUE THREAD

**Issue by hainho** [earthkingman/NodeJS-React-42StackOverFlow#175]
### 제목
formdata with no file cause error

### 이슈에 대한 설명
swagger 가 question upload 를 multipart/form-data 으로 요청하고 있는 상황에서
file upload api를 따로 분리하여 question upload는 file을 첨부하지 않고 file을 처리하는 로직도 없는 상황에서
swagger는 multipart/form-data 으로 요청하여 req.body의 내용을 읽어오지 못하는 버그 발생

swagger를 수정하여 application/json 방식으로 question upload 하도록 하여 해결됨
### checkList

- [x] front 에서도 post question, patch question, post answer, patch question API 요청시 application/json 방식으로 요청하도록 수정

**Comment by Chloekkk** [comment]
client 단도 변경하였습니다

**Comment by hainho** [comment]
request.body를 읽어오지 못하는 것이 아니라 request.file 을 못 읽어오는 것으로 확인되었습니다.
file 처리를 따로 할 시에는 file 관련 코드를 모두 지워 오류가 발생하지 않도록 해야합니다.
