### ISSUE TITLE
프로필 사진 저장 로직

### ISSUE THREAD

**Issue by hainho** [earthkingman/NodeJS-React-42StackOverFlow#177]
### 제목
프로필 사진 저장 로직

### 이슈에 대한 설명
현재 프로필 사진이 user.photo 에  저장 되는 방법은 3가지 입니다.
1. 42로그인을 통해 회원 가입 하며 42 프로필 사진이 저장
2. 프로필 업데이트를 통하여 프로필 사진 저장

1 번 방식은 42 주소 전체가 저장되고
2 번 방식은 s3 주소를 제외한 s3에 저장되는 위치가 저장되어

1번 방식으로 저장된 프로필 사진은 user.photo 응답시 그대로 가져와 응답하면 되고
2번 방식은 user.photo 데이터 앞에 s3 주소를 추가하여 응답하여야 합니다.

임시적으로 0번째 문자가 'h' 인지 확인하는 방법으로 둘을 구분 하였는데
이후 s3에 저장된 폴더의 이름이 h로 시작하게 된다면 버그 발생 가능성이 있어
s3에 저장한 주소를 db에 저장할때 s3 주소를 앞에 포함하여 추가하는 방식으로 수정 예정입니다.

**Comment by earthkingman** [comment]
회원가입경우 프로필을 설정할 수 있도록 구현되어있었는데 삭제하겠습니다!
