### ISSUE TITLE
https 서버 연결 에러

### ISSUE THREAD

**Issue by hainho** [earthkingman/NodeJS-React-42StackOverFlow#224]
### 제목
https 서버 연결 에러
### 이슈에 대한 설명
https 로 접속 가능하도록 설정 이후 실행시 프론트는 잘 실행이 되지만 서버에서 데이터를 가지고 오지 못함

<img width="1427" alt="스크린샷 2021-11-22 오전 2 40 24" src="https://user-images.githubusercontent.com/67993856/142773118-0109774f-9e2f-4210-bc5d-2989d2d029a1.png">

**Comment by hainho** [comment]
<img width="1246" alt="스크린샷 2021-11-22 오전 3 53 22" src="https://user-images.githubusercontent.com/67993856/142878131-3f8843f9-a885-4c49-aed1-3bc7172d8d33.png">

conf 파일을 수정한 뒤 nginx 재실행시 만난 에러

conf 파일 복사본을 42sof_copy.conf 이름으로 해두었는데 conf 파일이 두개라고 에러가 발생했습니다.

복사본 파일 이름을 변경하여 해결하였습니다.

**Comment by earthkingman** [comment]
![image](https://user-images.githubusercontent.com/48669085/142894575-0a714962-ada9-43f5-8d57-2165c3bf1244.png)
 백엔드 서버도 리버스 프록시 적용하면 될거 같습니다

**Comment by hainho** [comment]
사진과 같이 conf 파일 수정하고

기존의 라우터에 api/ 추가하여 해결되었습니다

감사합니다!!
