### ISSUE TITLE
댓글 수정 취소 버그

### ISSUE THREAD

**Issue by hainho** [earthkingman/NodeJS-React-42StackOverFlow#233]
### 제목
글 수정 삭제시 발생하는 버그
### 이슈에 대한 설명

- [x]  댓글 수정한 뒤 한번 더 수정하기 누른뒤 취소를 누르면 최초 작성한 댓글(수정 한번도 안한 댓글)로 보여졌다가 새로고침하면 수정한 댓글(수정 완료한 댓글)로 보여짐
- [x] 답변글 삭제시 답변글이 바로 사라지지 않고 그대로 노출되어 있다가 새로고침을 직접 해주어야 사라짐

**Comment by Yenowme** [comment]
모두 useSWR 의 `mutate` 사용시 해결 가능
