### ISSUE TITLE
이메일 변경시 유령계정 생성

### ISSUE THREAD

**Issue by earthkingman** [earthkingman/NodeJS-React-42StackOverFlow#236]
### 제목
이메일 변경시 유령계정 생성
### 이슈에 대한 설명
42API을 통해 회원가입과 로그인을 진행한다면 이메일을 변경하면 안됩니다.
![image](https://user-images.githubusercontent.com/48669085/143378050-9cba367a-094d-4127-b3e5-8a14ab41fbb4.png)

![image](https://user-images.githubusercontent.com/48669085/143378042-01a01f81-0218-49e4-a864-258f32225fd7.png)

기존에 있는 유저를 구분하기 위해선 email을 사용해야합니다.

**Comment by hainho** [comment]
해결방법

1. 이메일 변경 불가 하도록 설정
2. 유저 테이블에 42email 컬럼 추가하여 유저 식별용 email 추가하기
