### ISSUE TITLE
좋아요 빠른속도로 클릭하는 경우

### ISSUE THREAD

**Issue by earthkingman** [earthkingman/NodeJS-React-42StackOverFlow#255]
### 제목
좋아요 빠른속도로 클릭하는 경우
![image](https://user-images.githubusercontent.com/48669085/144187062-6eb8ea5b-d273-4ec9-a791-e8a54614503b.png)

### 이슈에 대한 설명
서버에서 응답을 하기전에 클라이언트에서 계속 요청을 보내면 오류가 발생합니다.
클라이언트에서 막아야할 것 같습니다.

**Comment by Yenowme** [comment]
클라이언트에서 `useSWR`의 기능인 `mutate`를 사용해서 누르자마자 데이터 업데이트 후 막아야할 것 같습니다. 수정하겠습니다

**Comment by Yenowme** [comment]
10초에 한번만 클릭 가능하도록 클라이언트에서 방지
