### ISSUE TITLE
User 프로필 사진 수정

### ISSUE THREAD

**Issue by earthkingman** [earthkingman/NodeJS-React-42StackOverFlow#26]
사용자 프로필 사진을 수정 했을 때 기존에 있던 사진을 삭제할지 그대로 둘지 고민입니다.

**Comment by hainho** [comment]
카카오톡 프로필 처럼 이전 프로필 사진을 볼 수 있는 기능은 크게 장점이 떠오르지 않습니다.

일단 mvp 기능을 완성한 뒤 프로젝트를 구체화 할 때 목적에 맞게 다시 고민해보는 것이 좋을 것 같습니다.
