### ISSUE TITLE
Pagination 구현에 관한 고찰

### ISSUE THREAD

**Issue by Chloekkk** [earthkingman/NodeJS-React-42StackOverFlow#47]
### 이슈에 대한 설명
- 서버에서 끊어서 데이터 가져올 것인지
- 클라이언트 단에서 다 처리할 것인지

**Comment by Yenowme** [comment]
## 결론 
- page=1일 때 서버로부터 전체 글 개수 받아와서 페이지 숫자 결정
- api 호출은 페이지 넘버 이동시마다 진행
