### ISSUE TITLE
웹팩에서 vite로 초기세팅 변경

### ISSUE THREAD

**Issue by Yenowme** [earthkingman/NodeJS-React-42StackOverFlow#64]
### vite 설정

- wepack에서 vite로 클라이언트 초기세팅 변경 (리액트 타입스크립트)

**Comment by kenu** [comment]
이거 좀 재밌어요.
`JavaScript 번들러로 본 조선시대 붕당의 이해`
![image](https://user-images.githubusercontent.com/718691/136531199-60ef8b99-8893-411d-b370-97e70c3c2087.png)

image from: https://wormwlrm.github.io/2020/08/12/History-of-JavaScript-Modules-and-Bundlers.html

**Comment by kenu** [comment]
Let's google it!
https://www.google.com/search?q=babel+vite
