### ISSUE TITLE
cypress 사용여부

### ISSUE THREAD

**Issue by Chloekkk** [earthkingman/NodeJS-React-42StackOverFlow#65]
### 이슈에 대한 설명
- cypress 란?

### checkList
- cypress 란 무엇인지
- 왜 사용하는지
- 어떻게 사용하는지
- 장점 및 단점

**Comment by kenu** [comment]
https://meetup.toast.com/posts/180
Unit Test(jest)까지만 신경쓰시고, cypress는 오픈 한 달 전에 도입하는 것을 추천합니다.
