### ISSUE TITLE
Detail page api 수정 요청

### ISSUE THREAD

**Issue by Yenowme** [earthkingman/NodeJS-React-42StackOverFlow#94]
### 이슈에 대한 설명
- 서버 통신 지속되면 db에 아래처럼 뜨면서 통신이 되지 않습니다. (오류와 연관된 메세지인진 확실하지 않음)
- node쪽에선 아무 오류도 안뜹니다. 
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/76904042/137885364-2837d243-5fa6-44a8-9e85-25e7b119bea4.png">

### checkList

- [x] questionDetail 꼭 필요한지? 필요하지 않으면 그냥 바로 data에 넣어서 전달하는게 더 깔끔할듯 합니다.
- [x] 어짜피 질문글 정보는 하나밖에 없으니까 questionDetail.questionInfo를 한개짜리 배열에서 객체로 수정 바랍니다. 
- [x] 변수들이 다 스웨거랑 다르게 camelCase 에서 언더바 사용하는 규칙으로 되어있는데 이것도 camelCase로 통일 바랍니다.

### 주의사항

- 수정 불가능한 사항 있으면 감안하고 진행할테니 말씀해주세요

**Comment by hainho** [comment]
DB 는 대체로 SNAKE_CASE 를 많이 사용한다고 하네요.

CAMEL_CASE 를 사용하는 프로젝트에서 DB 를 SNAKE_CASE 로 작성했을때 장점이
1. DB 예약어와 구분된다.
2. 데이터 베이스 데이터와 코드의 일반 변수 구분된다.

velog server 또한 CAMEL_CASE 를 사용하지만 DB 는 SNAKE_CASE 로 작성하였습니다.
https://github.com/velopert/velog-server/blob/master/src/entity/Post.ts
